apiVersion: v1
kind: Pod
metadata:
  name: bazzar.com
  namespace: bazzar
spec:
  containers:
    - name: jay-container
      image: jaydeepc1985/bazze:v1
      ports:
        - containerPort: 80
      
